### ISSUE TITLE
License

### ISSUE THREAD

**Issue by pchaigno** [artifactz/sublime-opal#3]
I would like to use your grammar for Opal but I don't know what licensing terms you're distributing it under. Any chance you could pick one from here: http://choosealicense.com?

**Comment by artifactz** [comment]
ok 55ae90b910933889d01c55766424db5b3e10332e

**Comment by pchaigno** [comment]
Thanks!

**Comment by pchaigno** [comment]
@artifactz Your grammar is now used to highlight Opal code on GitHub (files and code snippets in Markdown)! (See github/linguist#2089 for more information.)
